export interface EnvOccurrence {
  filePath: string;
  line: number;
  snippet: string;
}

export interface EnvVariable {
  name: string;
  occurrences: EnvOccurrence[];
}

const directPattern = /process\.env(?:\?\.)?\.([A-Z0-9_]+)/g;
const bracketPattern = /process\.env(?:\?\.)?\[['"]([A-Z0-9_]+)['"]\]/g;
const destructurePattern = /\{([^}]+)\}\s*=\s*process\.env\b/g;

function extractFromDestructuring(line: string): string[] {
  const vars: string[] = [];
  for (const match of line.matchAll(destructurePattern)) {
    const chunk = match[1] ?? "";
    const names = chunk
      .split(",")
      .map((part) => part.trim())
      .map((part) => part.split(":")[0]?.trim())
      .map((part) => part?.replace(/^[.]{3}/, ""))
      .filter((part): part is string => Boolean(part) && /^[A-Z0-9_]+$/.test(part));

    vars.push(...names);
  }
  return vars;
}

export function extractEnvReferencesFromContent(content: string, filePath: string): EnvVariable[] {
  const variableMap = new Map<string, EnvOccurrence[]>();
  const lines = content.split(/\r?\n/);

  lines.forEach((line, index) => {
    const names = new Set<string>();

    for (const match of line.matchAll(directPattern)) {
      if (match[1]) {
        names.add(match[1]);
      }
    }

    for (const match of line.matchAll(bracketPattern)) {
      if (match[1]) {
        names.add(match[1]);
      }
    }

    for (const name of extractFromDestructuring(line)) {
      names.add(name);
    }

    if (names.size === 0) {
      return;
    }

    for (const name of names) {
      const current = variableMap.get(name) ?? [];
      current.push({
        filePath,
        line: index + 1,
        snippet: line.trim().slice(0, 220)
      });
      variableMap.set(name, current);
    }
  });

  return [...variableMap.entries()]
    .map(([name, occurrences]) => ({ name, occurrences }))
    .sort((a, b) => a.name.localeCompare(b.name));
}

export function mergeEnvVariables(variables: EnvVariable[]): EnvVariable[] {
  const merged = new Map<string, EnvOccurrence[]>();

  for (const variable of variables) {
    const existing = merged.get(variable.name) ?? [];
    existing.push(...variable.occurrences);
    merged.set(variable.name, existing);
  }

  return [...merged.entries()]
    .map(([name, occurrences]) => ({
      name,
      occurrences: occurrences.slice(0, 8)
    }))
    .sort((a, b) => a.name.localeCompare(b.name));
}

export function buildEnvExample(
  variables: EnvVariable[],
  descriptions: Record<string, string>
): string {
  const lines: string[] = [
    "# Generated by Env Example Generator",
    "# Review before committing secrets or environment-specific values.",
    ""
  ];

  for (const variable of variables) {
    const description = descriptions[variable.name];
    if (description) {
      lines.push(`# ${description}`);
    }
    lines.push(`${variable.name}=`);
    lines.push("");
  }

  return lines.join("\n").trim() + "\n";
}
